apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: local-mkex-test
spec:
  hosts:
  - role: manager
    hooks:
      apply:
        before:
          - sudo docker load -i /usr/share/mke/ucp_images_3.7.0.tar.gz
          - sudo chown twizda /var/run/docker.sock
      reset:
        after:
          - sudo systemctl stop docker
          - sudo rm -rf /var/lib/docker
          - sudo systemctl start docker
    ssh:
      address: 192.168.1.24
      user: twizda
      keyPath: ~/.ssh/mcp
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      apply:
        before:
          - sudo docker load -i /usr/share/mke/ucp_images_3.7.0.tar.gz
          - sudo chown twizda /var/run/docker.sock
      reset:
        after:
          - sudo systemctl stop docker
          - sudo rm -rf /var/lib/docker
          - sudo systemctl start docker
    ssh:
      address: 192.168.1.25
      user: twizda
      keyPath: ~/.ssh/mcp
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      apply:
        before:
          - sudo docker load -i /usr/share/mke/ucp_images_3.7.0.tar.gz
          - sudo chown twizda /var/run/docker.sock
      reset:
        after:
          - sudo systemctl stop docker
          - sudo rm -rf /var/lib/docker
          - sudo systemctl start docker
    ssh:
      address: 192.168.1.26
      user: twizda
      keyPath: ~/.ssh/mcp
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      apply:
        before:
          - sudo docker load -i /usr/share/mke/ucp_images_3.7.0.tar.gz
          - sudo chown twizda /var/run/docker.sock
      reset:
        after:
          - sudo systemctl stop docker
          - sudo rm -rf /var/lib/docker
          - sudo systemctl start docker
    ssh:
      address: 192.168.1.28
      user: twizda
      keyPath: ~/.ssh/mcp
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      apply:
        before:
          - sudo docker load -i /usr/share/mke/ucp_images_3.7.0.tar.gz 
          - sudo chown twizda /var/run/docker.sock
      reset:
        after:
          - sudo systemctl stop docker
          - sudo rm -rf /var/lib/docker
          - sudo systemctl start docker
    ssh:
      address: 192.168.1.30
      user: twizda
      keyPath: ~/.ssh/mcp
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  mke:
    version: 3.7.0
    adminUsername: admin
    adminPassword: S#riouslyB@dP@ssw0rd
    installFlags:
      - --enable-profiling
      - --ingress-controller
      - --pod-cidr 9.0.3.0/24
      - --san 192.168.1.24
      - --san mke-mgr
    licenseFilePath: ./docker.lic
    configFile: ./mke-config.toml
  mcr:
    version: 23.0.7
    channel: stable
