apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: visa-mkex-test
spec:
  hosts:
  - role: manager
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 52.15.150.117
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 3.138.116.250
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  mke:
    version: 3.7.3
    adminUsername: admin
    adminPassword: T@n2thR#m1ngt0n
    installFlags:
      - --enable-profiling
      - --ingress-controller
      - --san 52.15.150.117
      - --san 172.31.0.10
      - --san ec2-52-15-150-117.us-east-2.compute.amazonaws.com
    licenseFilePath: ./docker.lic
    configFile: ./mke-config.toml
  mcr:
    version: 23.0.9
    channel: stable
