apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: abbvie-test
spec:
  hosts:
  - role: manager
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 18.217.10.114
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 18.223.238.255
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 18.118.207.78
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    ssh:
      address: 18.223.100.166
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
  mke:
    version: 3.6.5
    adminUsername: admin
    adminPassword: T@n2thR#m1ngt0n
    installFlags:
#      - --unmanaged-cni
#      - --enable-profiling
#      - --ingress-controller
      - --existing-config
      - --cloud-provider aws
      - --san 18.217.10.114
      - --san 172.31.14.146
      - --san ec2-18-217-10-114.us-east-2.compute.amazonaws.com
    licenseFilePath: ./docker.lic
    configFile: ./mke-config.toml
  mcr:
    version: 23.0.7
    channel: stable
