apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke+msr
metadata:
  name: sp-mke-msr
spec:
  hosts:
  - role: manager
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 3.145.17.210
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: msr
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 3.146.221.81
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  - role: worker
    hooks:
      reset:
        after:
          - sudo rm -rf /var/lib/docker
    ssh:
      address: 18.225.95.223
      user: docker
      keyPath: ~/.testkit/twizda-testkit.pem
    mcrConfig:
      experimental: true
      log-opts:
        max-size: 10m
        max-file: "3"
  mke:
    version: 3.6.5
    adminUsername: admin
    adminPassword: T@n2thR#m1ngt0n
    installFlags:
      - --enable-profiling
      - --ingress-controller
      - --san 3.145.17.210
      - --san 172.31.10.225
      - --san ec2-3-145-17-210.us-east-2.compute.amazonaws.com
    licenseFilePath: ./docker.lic
    configFile: ./mke-config.toml
  msr:
    version:  2.9.13
    installFlags:
      - --dtr-external-url ec2-3-146-221-81.us-east-2.compute.amazonaws.com
      - --ucp-insecure-tls
      - --ucp-node SP-MSR-rhel-1
      - --async-nfs
      - --enable-pprof
      - --nfs-storage-url nfs://172.31.6.152/var/nfs/msr
      - --nfs-options "rw,nfsvers=4,async"
  mcr:
    version: 23.0.6
    channel: stable
